### ISSUE TITLE
pf_sum_score_tree error

### ISSUE THREAD

**Issue by kingtom2016** [sfodel/phylo_z_scores#1]
Error: mapping and node can't be NULL simultaneously, we can't get the 
              data to be displayed in this layer, please provide a data or subset 
              (we will extract the data from tree data.), or provide node!

**Comment by sfodel** [comment]
Hello,

Thanks for this, the tree input argument was erroneous in Line 206.
I changed it to "tree = phy", please try it out now.

Cheers,
Stelios

**Comment by kingtom2016** [comment]
emm... Actually, I've noticed this wrong name, "phy_test", and I have tested using "tree = phy". Finally, I got the error mentioned above. Is this function OK on your data?

Ps: the nperm parameter is not used for the function. I think it should be "nreps".

Thanks for your replying.

**Comment by sfodel** [comment]
Oh yes you are right, I changed the "nperm: to "nreps"

Yes for my data it works but maybe it has to do with my workspace.
Other colleagues have issues with the whole script as a function, but not the error you mention just some errors with parallel.

Could you try running the commands individually (and load the subfunctions individually as well) and not as a single script and tell me if and where you get an error?

Thanks a lot,
Stelios

**Comment by kingtom2016** [comment]
Sorry I did not metion that actually, I ran the commands individually and find this error in the pf.tree() function

 pf_sum_score_tree <- pf.tree(pf_sum_score, tree= phy, layout='rectangular')

**Comment by sfodel** [comment]
I see,

Then it is simple I think, it has to do with the pf.tree function in package phylofactor.
I think I replaced mine, try the following function and let me know:

pf.tree2 <- function (pf, tree = NULL, method = "factors", factors = NULL, 
                    ignore.tips = TRUE, groups = NULL, colors = NULL, GroupList = NULL, 
                    bg.color = NA, bg.alpha = 0.1, alphas = NULL, layout = "circular", 
                    rootnode = FALSE, top.layer = F, top.alpha = 0.1, color.fcn = viridis::viridis, 
                    ...) 
{
  if (!(is.null(GroupList) & is.null(factors))) {
    if (method == "bins") {
      warning("input GroupList or factors will override method=\"bins\"")
      method = "factors"
    }
  }
  if (method == "factors") {
    if (is.null(GroupList)) {
      if (is.null(factors)) {
        if (is.null(groups)) {
          factor.map = data.frame(factor = 1:pf$nfactors, 
                                  group = rep(1, pf$nfactors))
        }
        else {
          factor.map = data.frame(factor = 1:pf$nfactors, 
                                  group = groups)
        }
      }
      else {
        if (is.null(groups)) {
          factor.map <- data.frame(factor = factors, 
                                   group = 1)
        }
        else {
          if (length(groups) != length(factors)) {
            stop("length of groups is not equal to length of factors")
          }
          else {
            factor.map <- data.frame(factor = factors, 
                                     group = groups)
          }
        }
      }
      m <- nrow(factor.map)
      if (is.null(colors)) {
        cols <- color.fcn(m)
        factor.map$colors <- cols
      }
      else {
        factor.map$colors <- colors
      }
    }
    else {
      m <- length(GroupList)
      method = "groups"
      if (is.null(colors)) {
        cols <- color.fcn(m)
      }
      else {
        cols <- colors
      }
      factor.map <- data.frame(Groups = 1:m, colors = cols, 
                               stringsAsFactors = F)
    }
  }
  if (method == "bins") {
    GroupList <- pf$bins
    method = "groups"
  }
  if (is.null(alphas)) {
    alphas <- rep(1, max((pf$nfactors + 1), length(GroupList)))
  }
  if (is.null(tree)) {
    tree = pf$tree
  }
  n = ape::Ntip(tree)
  nd <- NULL
  for (i in 1:m) {
    if (method == "factors") {
      grp <- pf$tree$tip.label[pf$groups[[factor.map[i, 
                                                     1]]][[factor.map[i, 2]]]]
    }
    else {
      grp <- pf$tree$tip.label[GroupList[[i]]]
    }
    grp <- intersect(grp, tree$tip.label)
    if (length(grp) > 0 & any(setdiff(tree$tip.label, grp) %in% 
                              pf$tree$tip.label)) {
      if (length(grp) > 1) {
        nd <- c(nd, ape::getMRCA(tree, grp))
      }
      else {
        nd <- c(nd, match(grp, tree$tip.label))
      }
    }
  }
  if (is.null(nd)) {
    stop("None of the factors/groups could be mapped to the input tree")
  }
  if (all(nd == (n + 1))) {
    stop("All factors/groups were mapped to the root of the input tree - no meaningful pf.tree to make")
  }
  ix <- order(nd, decreasing = F)
  nd <- nd[ix]
  gg <- ggtree::ggtree(tree, layout = layout, ...)
  if (nd[1] == (n + 1) | !is.na(bg.color)) {
    if (is.na(bg.color)) {
      bg.color = cols[1]
    }
    gg <- gg + ggtree::geom_hilight(n + 1, fill = bg.color, 
                                    alpha = bg.alpha)
  }
  i = 0
  for (ndd in nd) {
    i = i + 1
    if (!ndd == (n + 1) | rootnode) {
      gg <- gg + ggtree::geom_hilight(ndd, fill = cols[ix[i]], 
                                      alpha = alphas[i])
    }
  }
  gg <- gg + ggtree::geom_tree(...)
  if (top.layer) {
    i = 0
    for (ndd in nd) {
      i = i + 1
      if (!ndd == (n + 1) | rootnode) {
        gg <- gg + ggtree::geom_hilight(ndd, fill = cols[ix[i]], 
                                        alpha = top.alpha)
      }
    }
  }
  return(list(legend = factor.map, ggplot = gg))
}

Cheers,
Stelios

**Comment by kingtom2016** [comment]
It seems like the error is mainly caused by phylofactor under R version 4.0.3.   I try the script successfully under R 3.6.3.
Thanks for your replying.  :)

**Comment by sfodel** [comment]
Oh great! I will let the author of phylofactor know.
Enjoy the scripts and let me know if you need anything else.
I am therefore closing the issue now
Cheers,
Stelios
